import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import axios from "axios";
import { useRouter } from "next/router";

export default function Home() {
  const [apiData, setApiData] = useState([]);
  const [loadCount, setLoadCount] = useState(1);
  const [search, setsearch] = useState("");
  const [FiterData, setFilterData] = useState([]);

  const navigate = useRouter();

  useEffect(() => {
    axios.get("https://restcountries.com/v3.1/all").then((res) => {
      setApiData(res?.data);
    });
  }, []);

  useEffect(() => {
    if (search?.length > 1) {
      const filter = apiData.filter((items) =>
        ((items?.name?.common).toLowerCase()).includes(search)
      );
      setFilterData(filter.slice(0, 10 * loadCount));
    } else {
      setFilterData(apiData.slice(0, 10* loadCount));
    }
  }, [search, loadCount,apiData]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Interview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="">
        <h1>Interview</h1>
        <div className="d-flex justify-content-center">
          <input
            onChange={(e) => setsearch(e.target.value)}
            className="input-search"
            placeholder="Search Here"
          ></input>
        </div>
        <div
          className="d-flex list-card"
          style={{
            padding: "20px",
            gap: "20px",
            overflow: "auto",
            width: "max-content",
          }}
        >
          {FiterData?.map((items,i) => (
            <div
            key={i}
              onClick={() => navigate.push(items?.name?.common)}
              className="Card d-flex"
            >
              <div
                className="d-flex align-items-center"
                style={{ height: "50%" }}
              >
                <img
                  alt="image"
                  src={items?.flags?.png}
                  width={"100%"}
                  height={"200px"}
                  style={{
                    width: "226px",
                    height: "200px",
                    objectFit: "contain",
                  }}
                ></img>
              </div>
              <h3 style={{marginTop:"30px"}}>{items?.name?.common}</h3>
            </div>
          ))}
          <button
            className="load-more"
            onClick={() => setLoadCount((pre) => pre + 1)}
          >
            +
          </button>
        </div>
      </div>
    </div>
  );
}
